---
title: "Historical vs Currrent"
output: html_document
---

### The Contiguous United States

##### Ecosystems are constantly changing and adapting whether it's slowly and minutely or abrubtly and drastically. Changes  


#### Comparison of ecosystems historically vs now

```{r}
library(DataCombine)
library(reshape2)
library(plotly)
#Making a new dataset with historical acres and then another with current

hist <- BPSclean[, c(2, 6)]
cur <- EVTClean[, c(3, 5)]

#summing classes together

colnames(hist)[colnames(hist)=="BPS_NAME"] <- "CLASSNAME"

hist <- hist %>%
  group_by(CLASSNAME) %>%
    summarise(sum(COUNT))

cur <- cur %>%
  group_by(CLASSNAME) %>%
    summarise(sum(COUNT))

#renaming columns

colnames(hist)[colnames(hist)=="sum(COUNT)"] <- "COUNT_HIST"

colnames(cur)[colnames(cur)=="sum(COUNT)"] <- "COUNT_CURR"

#cur$GROUPVEG[ c(626:639)] <- "Sparse"

#tail(hist)
comp <- merge(hist, cur, by  = "CLASSNAME", all = TRUE)
comp[is.na(comp)] <- 0

#problem is in the merge dropping values
BPSclean <- mutate(BPSclean, ACRES = COUNT *0.222)
comp <- mutate(comp, ACRES_HIST = COUNT_HIST * 0.222)
comp <- mutate(comp, ACRES_CURR = COUNT_CURR * 0.222)

comp <- comp[-c(503), -c(2, 3)]


#reodering the comp data set in descending order according to historical acres
comp <- comp[order(-comp$ACRES_HIST),]

#adding diff column
comp$DIFF <- abs(comp[, 3] - comp[, 2])




#head(comp)
#tail(comp)

#p <- plot_ly(comp, x = ~ACRES_CURR, y = ~DIFF, text = ~paste("Ecosystem: ", CLASSNAME, "<br> Historical Acres: ", ACRES_HIST))

#p

#totalAcres <- sum(comp$ACRES_HIST)

#comp <- comp[!(sum(comp$ACRES_HIST) >=  ]

#comp.long <- melt(comp)

#colnames(comp.long)[colnames(comp.long) == "value"] <- "ACRES"

# Dear Mat, you need to change that freaking column name from "sum(value)" to something more better.  Is "comp.long" the change?

#eco <- ggplot(comp.long, aes(fill = variable, y = ACRES, x = reorder(CLASSNAME, ACRES, function(x){sum(x)}))) + geom_bar(position = "dodge", stat="identity") + coord_flip() + xlab("Ecosystem")


#eco

```

```{r}
#head(comp.long)
#colnames(comp.long)
```

